#!/usr/bin/env bash
set -euo pipefail

WIDTH="${WIDTH:-256}"
HEIGHT="${HEIGHT:-256}"
EPISODE_STEPS="${EPISODE_STEPS:-5000}"
BASE_SEEDS="${BASE_SEEDS:-40 41 42}"
EPISODES_PER_SEED="${EPISODES_PER_SEED:-3}"
SEED_STRIDE="${SEED_STRIDE:-100}"
RUN_HEATMAPS="${RUN_HEATMAPS:-0}"
RUN_EVALUATIONS="${RUN_EVALUATIONS:-0}"
START_UTC="${START_UTC:-2026-01-01T00:00:00Z}"
# A simulation step represents one minute. Avoid padded target windows after
# the recorded simulation, which otherwise create an artificially empty test tail.
END_UTC="${END_UTC:-$(date -u -d "${START_UTC} + ${EPISODE_STEPS} minutes" '+%Y-%m-%dT%H:%M:%SZ')}"
WINDOW_SECONDS="${WINDOW_SECONDS:-3600}"

# Stationarity profile: slower background fill, more frequent bottom-layer removal,
# and sparse direct-event extraction. Localized sources remain enabled.
TARGET_FILL_LIMIT="${TARGET_FILL_LIMIT:-$(( WIDTH * HEIGHT / 128 ))}"
TARGET_FILL_MODE="${TARGET_FILL_MODE:-sources}"
BOTTOM_LAYER_INTERVAL="${BOTTOM_LAYER_INTERVAL:-25}"
DEPOSITION_PROBABILITY="${DEPOSITION_PROBABILITY:-0.45}"
DEPOSITION_MODE="${DEPOSITION_MODE:-sources}"
SOURCE_COUNT="${SOURCE_COUNT:-$(( WIDTH * HEIGHT / 64 ))}"
INITIAL_FILL_MODE="${INITIAL_FILL_MODE:-none}"
INITIAL_FILL_MEAN_HEIGHT="${INITIAL_FILL_MEAN_HEIGHT:-0}"
INITIAL_FILL_VARIATION="${INITIAL_FILL_VARIATION:-0}"
INITIAL_FILL_SMOOTH_PASSES="${INITIAL_FILL_SMOOTH_PASSES:-0}"
WARMUP_STEPS="${WARMUP_STEPS:-3000}"
DAMAGE_ENABLED="${DAMAGE_ENABLED:-0}"
DAMAGE_ACTIVATION_RATIO="${DAMAGE_ACTIVATION_RATIO:-0.85}"
DAMAGE_DECAY="${DAMAGE_DECAY:-0.985}"
DAMAGE_COUPLING="${DAMAGE_COUPLING:-0.10}"
DAMAGE_THRESHOLD_REDUCTION="${DAMAGE_THRESHOLD_REDUCTION:-0.25}"
DAMAGE_RESET_FRACTION="${DAMAGE_RESET_FRACTION:-0.90}"
EVENT_QUANTILE="${EVENT_QUANTILE:-0.999}"
EVENT_WINDOW="${EVENT_WINDOW:-240}"
EVENT_MAX="${EVENT_MAX:-5}"

episode_seeds=()
for base_seed in $BASE_SEEDS; do
  for episode_index in $(seq 0 $((EPISODES_PER_SEED - 1))); do
    seed=$((base_seed * SEED_STRIDE + episode_index))
    episode_seeds+=("$seed")
    echo "synthetic episode: base_seed=$base_seed episode=$episode_index seed=$seed"
    WIDTH="$WIDTH" \
    HEIGHT="$HEIGHT" \
    STEPS="$EPISODE_STEPS" \
    SEED="$seed" \
    RUN_HEATMAPS="$RUN_HEATMAPS" \
    TARGET_FILL_LIMIT="$TARGET_FILL_LIMIT" \
    TARGET_FILL_MODE="$TARGET_FILL_MODE" \
    BOTTOM_LAYER_INTERVAL="$BOTTOM_LAYER_INTERVAL" \
    DEPOSITION_PROBABILITY="$DEPOSITION_PROBABILITY" \
    DEPOSITION_MODE="$DEPOSITION_MODE" \
    SOURCE_COUNT="$SOURCE_COUNT" \
    INITIAL_FILL_MODE="$INITIAL_FILL_MODE" \
    INITIAL_FILL_MEAN_HEIGHT="$INITIAL_FILL_MEAN_HEIGHT" \
    INITIAL_FILL_VARIATION="$INITIAL_FILL_VARIATION" \
    INITIAL_FILL_SMOOTH_PASSES="$INITIAL_FILL_SMOOTH_PASSES" \
    WARMUP_STEPS="$WARMUP_STEPS" \
    DAMAGE_ENABLED="$DAMAGE_ENABLED" \
    DAMAGE_ACTIVATION_RATIO="$DAMAGE_ACTIVATION_RATIO" \
    DAMAGE_DECAY="$DAMAGE_DECAY" \
    DAMAGE_COUPLING="$DAMAGE_COUPLING" \
    DAMAGE_THRESHOLD_REDUCTION="$DAMAGE_THRESHOLD_REDUCTION" \
    DAMAGE_RESET_FRACTION="$DAMAGE_RESET_FRACTION" \
      ./scripts/sim.sh
  done
done

SEEDS="${episode_seeds[*]}" \
WIDTH="$WIDTH" \
HEIGHT="$HEIGHT" \
STEPS="$EPISODE_STEPS" \
START_UTC="$START_UTC" \
END_UTC="$END_UTC" \
WINDOW_SECONDS="$WINDOW_SECONDS" \
EVENT_QUANTILE="$EVENT_QUANTILE" \
EVENT_WINDOW="$EVENT_WINDOW" \
EVENT_MAX="$EVENT_MAX" \
RUN_EVENT_MAPS=0 \
RUN_EVALUATIONS="$RUN_EVALUATIONS" \
  ./scripts/refresh-synthetic-model-artifacts.sh
