#!/usr/bin/env bash
set -euo pipefail

# CPU-only larger synthetic batch for Transformer pretraining experiments.
WIDTH="${WIDTH:-256}"
HEIGHT="${HEIGHT:-256}"
EPISODE_STEPS="${EPISODE_STEPS:-6000}"
BASE_SEEDS="${BASE_SEEDS:-40 41 42 43 44}"
EPISODES_PER_SEED="${EPISODES_PER_SEED:-4}"
WARMUP_STEPS="${WARMUP_STEPS:-3000}"
RUN_HEATMAPS="${RUN_HEATMAPS:-0}"
RUN_EVALUATIONS="${RUN_EVALUATIONS:-0}"

WIDTH="$WIDTH" \
HEIGHT="$HEIGHT" \
EPISODE_STEPS="$EPISODE_STEPS" \
BASE_SEEDS="$BASE_SEEDS" \
EPISODES_PER_SEED="$EPISODES_PER_SEED" \
WARMUP_STEPS="$WARMUP_STEPS" \
RUN_HEATMAPS="$RUN_HEATMAPS" \
RUN_EVALUATIONS="$RUN_EVALUATIONS" \
  ./scripts/run-synthetic-episode-batch.sh
